groups:
- name: /etc/prometheus/mongo_alert.rules
  rules:
  - alert: MongoInstanceDown
    expr: up{job="mongodb_exporter"} == 0
    for: 5m
    labels:
      severity: critical
    annotations:
      description: '{{ $labels.instance }} of job {{ $labels.job }} has been down
        for more than 5 minutes.'
      summary: MongoInstance {{ $labels.instance  }} down
